ARG INSTALLED_IMAGE=localhost/polly-debian-installed-base
FROM ${INSTALLED_IMAGE}
USER root
COPY release/storage/early-usr /etc/initramfs-tools/scripts/local-bottom/polly-storage-usr
COPY release/storage/initramfs-hook /etc/initramfs-tools/hooks/polly-storage-tools
COPY release/storage/layout.py release/storage/storage.py /usr/lib/polly-storage/
COPY release/storage/polly-storage.service /etc/systemd/system/
COPY release/storage/apt-storage.conf /etc/apt/apt.conf.d/00polly-storage
RUN sed -i 's/\r$//' /etc/initramfs-tools/scripts/local-bottom/polly-storage-usr \
        /etc/initramfs-tools/hooks/polly-storage-tools /usr/lib/polly-storage/*.py \
        /etc/systemd/system/polly-storage.service /etc/apt/apt.conf.d/00polly-storage && \
    chmod 755 /etc/initramfs-tools/scripts/local-bottom/polly-storage-usr \
        /etc/initramfs-tools/hooks/polly-storage-tools /usr/lib/polly-storage/storage.py && \
    chmod 644 /usr/lib/polly-storage/layout.py /etc/systemd/system/polly-storage.service \
        /etc/apt/apt.conf.d/00polly-storage && \
    ln -s ../lib/polly-storage/storage.py /usr/sbin/polly-storage && \
    systemctl enable polly-storage.service && \
    update-initramfs -u -k all
ENTRYPOINT []
CMD ["/bin/sh"]
