[Unit]
After=polly-hardware-log.service systemd-logind.service
Wants=polly-hardware-log.service systemd-logind.service

[Service]
ExecStart=
ExecStart=-/sbin/agetty --autologin polly --noclear %I linux
