/* Generated by desktop/tools/generate-decoration-themes.mjs. */
#ifndef POLLYWM_DECORATION_THEMES_H
#define POLLYWM_DECORATION_THEMES_H
#include "appearance-config.h"
static const struct PuDecorationTheme pu_decoration_themes[] = {
    { .id = "xp",
      .border_width = 3, .title_height = 32, .radius = 8, .control_size = 24, .control_gap = 4, .control_inset = 6, .control_radius = 4, .text_inset = 10, .text_gap = 8, .font_size = 13, .font_weight = 400, .stripe_spacing = 3, .stripe_width = 1, .glyph_radius = 4, .glyph_thickness = 0.7, .close_thickness = 0.8, .hover_opacity = 0.25, .inactive_opacity = 0.55, .stripe_opacity = 0.12,
      .left_controls = false, .round_controls = false,
      .pinstripe = false, .horizontal = false,
      .glyphs_hover = false,
      .font_family = 0,
      .text_align = 0,
      .border = 0xff1649adu, .titleFrom = 0xff4396ffu, .titleTo = 0xff1252c9u, .titleText = 0xffffffffu, .inactiveFrom = 0xffa8c3e9u, .inactiveTo = 0xff6e96cfu, .inactiveText = 0xff172d54u, .controlFrom = 0xff82b9ffu, .controlTo = 0xff2862c9u, .closeFrom = 0xfff99b7du, .closeTo = 0xffcf4628u, .controlText = 0xffffffffu, .minimizeFrom = 0xff82b9ffu, .minimizeTo = 0xff2862c9u, .maximizeFrom = 0xff82b9ffu, .maximizeTo = 0xff2862c9u, .hoverColor = 0xffffffffu, .stripeColor = 0xffaabbccu },
    { .id = "server2003",
      .border_width = 3, .title_height = 27, .radius = 0, .control_size = 19, .control_gap = 4, .control_inset = 6, .control_radius = 0, .text_inset = 10, .text_gap = 8, .font_size = 13, .font_weight = 400, .stripe_spacing = 3, .stripe_width = 1, .glyph_radius = 4, .glyph_thickness = 0.7, .close_thickness = 0.8, .hover_opacity = 0.25, .inactive_opacity = 0.55, .stripe_opacity = 0.12,
      .left_controls = false, .round_controls = false,
      .pinstripe = false, .horizontal = false,
      .glyphs_hover = false,
      .font_family = 0,
      .text_align = 0,
      .border = 0xff74716bu, .titleFrom = 0xff0a246au, .titleTo = 0xffa6c8dfu, .titleText = 0xffffffffu, .inactiveFrom = 0xff7e7d79u, .inactiveTo = 0xffc5c3bcu, .inactiveText = 0xffffffffu, .controlFrom = 0xffeeebe5u, .controlTo = 0xffbbb8b0u, .closeFrom = 0xffeeebe5u, .closeTo = 0xffbbb8b0u, .controlText = 0xff151515u, .minimizeFrom = 0xffeeebe5u, .minimizeTo = 0xffbbb8b0u, .maximizeFrom = 0xffeeebe5u, .maximizeTo = 0xffbbb8b0u, .hoverColor = 0xffffffffu, .stripeColor = 0xffaabbccu },
    { .id = "aqua",
      .border_width = 1, .title_height = 32, .radius = 10, .control_size = 14, .control_gap = 4, .control_inset = 6, .control_radius = 8, .text_inset = 10, .text_gap = 8, .font_size = 13, .font_weight = 400, .stripe_spacing = 3, .stripe_width = 1, .glyph_radius = 4, .glyph_thickness = 0.7, .close_thickness = 0.8, .hover_opacity = 0.25, .inactive_opacity = 0.55, .stripe_opacity = 0.12,
      .left_controls = true, .round_controls = true,
      .pinstripe = true, .horizontal = false,
      .glyphs_hover = true,
      .font_family = 0,
      .text_align = 0,
      .border = 0xff7b91a4u, .titleFrom = 0xffffffffu, .titleTo = 0xffd9e2e9u, .titleText = 0xff202934u, .inactiveFrom = 0xfff4f6f8u, .inactiveTo = 0xffe9edf0u, .inactiveText = 0xff667584u, .controlFrom = 0xffffffffu, .controlTo = 0xffd1dce6u, .closeFrom = 0xffffb1a8u, .closeTo = 0xffd84b43u, .controlText = 0xff582c24u, .minimizeFrom = 0xffffdc76u, .minimizeTo = 0xffeab63du, .maximizeFrom = 0xff83dc93u, .maximizeTo = 0xff42b964u, .hoverColor = 0xffffffffu, .stripeColor = 0xffaabbccu },
    { .id = "lion",
      .border_width = 1, .title_height = 30, .radius = 6, .control_size = 14, .control_gap = 4, .control_inset = 6, .control_radius = 8, .text_inset = 10, .text_gap = 8, .font_size = 13, .font_weight = 400, .stripe_spacing = 3, .stripe_width = 1, .glyph_radius = 4, .glyph_thickness = 0.7, .close_thickness = 0.8, .hover_opacity = 0.25, .inactive_opacity = 0.55, .stripe_opacity = 0.12,
      .left_controls = true, .round_controls = true,
      .pinstripe = false, .horizontal = false,
      .glyphs_hover = true,
      .font_family = 0,
      .text_align = 0,
      .border = 0xff777d85u, .titleFrom = 0xffe6e7e9u, .titleTo = 0xffb7bbc0u, .titleText = 0xff2e333au, .inactiveFrom = 0xffe5e6e8u, .inactiveTo = 0xffcfd1d5u, .inactiveText = 0xff68717cu, .controlFrom = 0xfff4f5f7u, .controlTo = 0xffbfc4cbu, .closeFrom = 0xfff99c91u, .closeTo = 0xffc9564bu, .controlText = 0xff532822u, .minimizeFrom = 0xffffdc76u, .minimizeTo = 0xffeab63du, .maximizeFrom = 0xff83dc93u, .maximizeTo = 0xff42b964u, .hoverColor = 0xffffffffu, .stripeColor = 0xffaabbccu },
    { .id = "bigsur",
      .border_width = 1, .title_height = 40, .radius = 14, .control_size = 14, .control_gap = 4, .control_inset = 6, .control_radius = 8, .text_inset = 10, .text_gap = 8, .font_size = 13, .font_weight = 400, .stripe_spacing = 3, .stripe_width = 1, .glyph_radius = 4, .glyph_thickness = 0.7, .close_thickness = 0.8, .hover_opacity = 0.25, .inactive_opacity = 0.55, .stripe_opacity = 0.12,
      .left_controls = true, .round_controls = true,
      .pinstripe = false, .horizontal = false,
      .glyphs_hover = true,
      .font_family = 0,
      .text_align = 0,
      .border = 0xffb1b9c6u, .titleFrom = 0xfff5f6f8u, .titleTo = 0xfff5f6f8u, .titleText = 0xff303745u, .inactiveFrom = 0xffedeff3u, .inactiveTo = 0xffedeff3u, .inactiveText = 0xff6f7886u, .controlFrom = 0xfff4f6fau, .controlTo = 0xffe0e6efu, .closeFrom = 0xffff837bu, .closeTo = 0xfff15b52u, .controlText = 0xff592c28u, .minimizeFrom = 0xffffdc76u, .minimizeTo = 0xffeab63du, .maximizeFrom = 0xff83dc93u, .maximizeTo = 0xff42b964u, .hoverColor = 0xffffffffu, .stripeColor = 0xffaabbccu },
};
#define PU_DECORATION_THEME_COUNT (sizeof(pu_decoration_themes) / sizeof(pu_decoration_themes[0]))
#define PU_DECORATION_DEFAULT_THEME 0
#endif
