/* Generated by desktop/tools/generate-decoration-themes.mjs. */
#ifndef POLLYWM_DECORATION_THEMES_H
#define POLLYWM_DECORATION_THEMES_H
#include <stdbool.h>
#include <stdint.h>

struct PuDecorationTheme {
    const char *id;
    int border_width, title_height, radius;
    bool left_controls, round_controls, pinstripe;
    uint32_t border, titleFrom, titleTo, titleText, inactiveFrom, inactiveTo, inactiveText, controlFrom, controlTo, closeFrom, closeTo, controlText;
};
static const struct PuDecorationTheme pu_decoration_themes[] = {
    { "xp", 3, 32, 8,
      false, false, false,
      0xff1649adu, 0xff4396ffu, 0xff1252c9u, 0xffffffffu, 0xffa8c3e9u, 0xff6e96cfu, 0xff172d54u, 0xff82b9ffu, 0xff2862c9u, 0xfff99b7du, 0xffcf4628u, 0xffffffffu },
    { "server2003", 3, 27, 0,
      false, false, false,
      0xff74716bu, 0xff0a246au, 0xffa6c8dfu, 0xffffffffu, 0xff7e7d79u, 0xffc5c3bcu, 0xffffffffu, 0xffeeebe5u, 0xffbbb8b0u, 0xffeeebe5u, 0xffbbb8b0u, 0xff151515u },
    { "aqua", 1, 32, 10,
      true, true, true,
      0xff7b91a4u, 0xffffffffu, 0xffd9e2e9u, 0xff202934u, 0xfff4f6f8u, 0xffe9edf0u, 0xff667584u, 0xffffffffu, 0xffd1dce6u, 0xffffb1a8u, 0xffd84b43u, 0xff582c24u },
    { "lion", 1, 30, 6,
      true, true, false,
      0xff777d85u, 0xffe6e7e9u, 0xffb7bbc0u, 0xff2e333au, 0xffe5e6e8u, 0xffcfd1d5u, 0xff68717cu, 0xfff4f5f7u, 0xffbfc4cbu, 0xfff99c91u, 0xffc9564bu, 0xff532822u },
    { "bigsur", 1, 40, 14,
      true, true, false,
      0xffb1b9c6u, 0xfff5f6f8u, 0xfff5f6f8u, 0xff303745u, 0xffedeff3u, 0xffedeff3u, 0xff6f7886u, 0xfff4f6fau, 0xffe0e6efu, 0xffff837bu, 0xfff15b52u, 0xff592c28u },
};
#define PU_DECORATION_THEME_COUNT (sizeof(pu_decoration_themes) / sizeof(pu_decoration_themes[0]))
#define PU_DECORATION_DEFAULT_THEME 0
#endif
