"""Generate FileSystem metadata on native Linux x86_64/LP64, using its C headers.

Run: python3 sysrt/tools/generate-files-abi.py [--cc clang] [--check]
CC may select a compiler command. No cross-compilation or header fallback.
"""
import argparse
import ctypes
import json
import os
from pathlib import Path
import platform
import shlex
import subprocess
import sys
import tempfile


OUTPUT = Path(__file__).resolve().parents[1] / "bindings" / "generated" / "files-linux-x86_64.mjs"
FIELDS = (
    ("mask", "stx_mask", "u32"), ("links", "stx_nlink", "u32"),
    ("uid", "stx_uid", "u32"), ("gid", "stx_gid", "u32"),
    ("mode", "stx_mode", "u16"), ("inode", "stx_ino", "u64"),
    ("size", "stx_size", "u64"), ("ctimeSeconds", "stx_ctime.tv_sec", "i64"),
    ("ctimeNanos", "stx_ctime.tv_nsec", "u32"), ("mtimeSeconds", "stx_mtime.tv_sec", "i64"),
    ("mtimeNanos", "stx_mtime.tv_nsec", "u32"), ("deviceMajor", "stx_dev_major", "u32"),
    ("deviceMinor", "stx_dev_minor", "u32"),
)
CONSTANTS = (
    "AT_FDCWD", "AT_EMPTY_PATH", "AT_SYMLINK_NOFOLLOW", "AT_EACCESS", "AT_REMOVEDIR",
    "STATX_BASIC_STATS", "O_RDONLY", "O_RDWR", "O_WRONLY", "O_CREAT", "O_EXCL",
    "O_TRUNC", "O_APPEND", "O_NONBLOCK", "O_DIRECTORY", "O_NOFOLLOW", "O_CLOEXEC",
    "O_PATH", "RENAME_NOREPLACE", "SEEK_SET", "SEEK_CUR", "SEEK_END",
    "S_IFMT", "S_IFREG", "S_IFDIR", "S_IFLNK", "LOCK_EX", "LOCK_NB",
)


def require_native_target():
    if (sys.platform != "linux" or platform.machine() != "x86_64" or
            ctypes.sizeof(ctypes.c_void_p) != 8 or ctypes.sizeof(ctypes.c_long) != 8 or
            sys.byteorder != "little"):
        raise ValueError("FileSystem ABI generation requires native Linux x86_64/LP64 (little-endian)")


def probe_source():
    lines = [
        "#define _GNU_SOURCE 1",
        "#if !defined(__linux__) || !defined(__x86_64__) || !defined(__LP64__) || defined(__ILP32__)",
        '#error "FileSystem ABI compiler target must be Linux x86_64/LP64"',
        "#endif",
        "#include <fcntl.h>", "#include <limits.h>", "#include <stddef.h>",
        "#include <stdio.h>", "#include <sys/stat.h>", "#include <sys/file.h>", "#include <unistd.h>",
        '_Static_assert(CHAR_BIT == 8 && sizeof(void *) == 8 && sizeof(long) == 8, "LP64 required");',
    ]
    for name, member, kind in FIELDS:
        expression = f"((struct statx *)0)->{member}"
        signed = ("_Generic(" + expression +
                  ", signed char: 1, short: 1, int: 1, long: 1, long long: 1,"
                  " unsigned char: 0, unsigned short: 0, unsigned int: 0,"
                  " unsigned long: 0, unsigned long long: 0, default: -1)")
        lines.append(f'_Static_assert(sizeof({expression}) == {int(kind[1:]) // 8} && '
                     f'{signed} == {int(kind[0] == "i")}, "statx {name} type mismatch");')
    lines.extend([
        "int main(void) {",
        'printf("pointerSize %zu\\nlongSize %zu\\nstatxSize %zu\\n", sizeof(void *), sizeof(long), sizeof(struct statx));',
    ])
    for name, member, _ in FIELDS:
        lines.append(f'printf("{name} %zu\\n", offsetof(struct statx, {member}));')
    for macro in CONSTANTS:
        lines.append(f'printf("{macro} %lld\\n", (long long)({macro}));')
    lines.extend(["return 0;", "}"])
    return "\n".join(lines) + "\n"


def measure(compiler):
    require_native_target()
    command = shlex.split(compiler)
    if not command:
        raise ValueError("A target C compiler command is required")
    with tempfile.TemporaryDirectory(prefix="polly-files-abi-") as temporary:
        source, executable = Path(temporary) / "probe.c", Path(temporary) / "probe"
        source.write_text(probe_source(), encoding="ascii")
        subprocess.run([*command, "-std=c11", "-Wall", "-Wextra", "-Werror", str(source), "-o", str(executable)],
                       check=True, timeout=30)
        output = subprocess.run([str(executable)], check=True, capture_output=True,
                                text=True, encoding="ascii", timeout=30).stdout
    rows = [line.split() for line in output.splitlines()]
    expected = ["pointerSize", "longSize", "statxSize", *[name for name, _, _ in FIELDS], *CONSTANTS]
    if any(len(row) != 2 for row in rows) or [row[0] for row in rows] != expected:
        raise ValueError("Unexpected FileSystem ABI probe output")
    return {name: int(value) for name, value in rows}


def render(values):
    target = {"architecture": "x86_64", "pointerSize": values["pointerSize"], "longSize": values["longSize"]}
    layout = {"statx": {"byteLength": values["statxSize"], "fields": {
        name: {"type": kind, "offset": values[name]} for name, _, kind in FIELDS
    }}}
    constants = {name: values[name] for name in CONSTANTS}
    return ("// Generated by sysrt/tools/generate-files-abi.py; do not edit.\n"
            "// Target: native Linux x86_64/LP64; measured from target C headers.\n"
            f"export const fileAbiTarget = {json.dumps(target, indent=2)};\n\n"
            f"export const fileAbiLayouts = {json.dumps(layout, indent=2)};\n\n"
            f"export const nativeFileConstants = Object.freeze({json.dumps(constants, indent=2)});\n").encode("ascii")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cc", default=os.environ.get("CC", "cc"), help="Native target C compiler command (default: CC or cc)")
    parser.add_argument("--output", type=Path, default=OUTPUT, help="Generated JS module path")
    parser.add_argument("--check", action="store_true", help="Fail if output is missing or differs; do not write")
    args = parser.parse_args()
    try:
        content = render(measure(args.cc))
        if args.check:
            if not args.output.is_file() or args.output.read_bytes() != content:
                raise ValueError("Generated FileSystem ABI is missing or stale; run generate-files-abi.py on the target")
        else:
            args.output.parent.mkdir(parents=True, exist_ok=True)
            args.output.write_bytes(content)
    except (OSError, ValueError, subprocess.SubprocessError) as error:
        print(f"FileSystem ABI generation failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
